version: "3"
services:
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  web:
    container_name: web
    build: .
    ports:
      -  "80:80"
    links:
      - mongo
    command: npm start
 
