version: "3"
services:
  web:
    container_name: web
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
    command: npm start
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"