apiVersion: v1
kind: ReplicationController
metadata:
  name: mongo-master
  labels:
    name: mongo-master
spec:
  replicas: 1
  selector:
    name: mongo-master
  template:
    metadata:
      labels:
        name: mongo-master
    spec:
      containers:
      - name: master
        image: mongo
        ports:
        - containerPort: 27017
