apiVersion: v1
kind: Service
metadata:
  name: nodejs
  labels:
    name: nodejs
spec:
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
  # type: LoadBalancer
  type: NodePort
  ports:
    # the port that this service should serve on
    - port: 3000
      nodePort: 3000
  selector:
    name: nodejs
